apiVersion: v1
kind: Service
metadata:
  name: os-dbaas-monitor-grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: os-dbaas-monitor-grafana
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 30000
      targetPort: 3000
      protocol: TCP
  selector:
    app: os-dbaas-monitor-grafana
