apiVersion: v1
kind: Service
metadata:
  name: os-dbaas-monitor-prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: os-dbaas-monitor-prometheus
spec:
  selector:
    app: os-dbaas-monitor-prometheus
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: config
      protocol: TCP
      port: 8080
      targetPort: 8080
