{
 "title": "MySQL Overview",
 "tags": [ "MySQL" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "主机资源监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "系统启动时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=\"$host\"} * 1000",
     "legendFormat": "System Uptime(days)"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$host\"} - (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"})) / node_memory_MemTotal_bytes{instance=\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "缓存占比",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_Cached_bytes{instance=\"$host\"} * 100) / node_memory_MemTotal_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Swap利用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$host\"} - node_memory_SwapFree_bytes{instance=~\"$host\"}) / (node_memory_SwapTotal_bytes{instance=~\"$host\"} + 1) *100"
    }
   ]
  },
  {
   "title": "CPU 核心数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$host\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "系统平均负载 (1,5,15) ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$host\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$host\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$host\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{instance=\"$host\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "磁盘使用情况",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance='$host',fstype=~\"ext3|ext4|xfs|nfs\"})/100 *100"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance='$host',fstype=~\"ext3|ext4|xfs|nfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance='$host',fstype=~\"ext3|ext4|xfs|nfs\"} / node_filesystem_size_bytes{instance='$host',fstype=~\"ext3|ext4|xfs|nfs\"})"
    }
   ]
  },
  {
   "title": "磁盘IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ops", "label": "read/ write" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{device}}_write"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$host\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "磁盘带宽",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "read/ write" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total {instance=~\"$host\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "磁盘耗时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "read/ write" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m]) *1000",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m]) *1000",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  { "title": "Mysql基本运行信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "MySQL启动时间",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 28 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()* 1000-mysql_global_status_uptime{instance=\"$host\"} * 1000"
    }
   ]
  },
  {
   "title": "MySQL版本",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "mysql_version_info{instance=\"$host\"}",
     "legendFormat": "{{innodb_version}}"
    }
   ]
  },
  {
   "title": "运行状态",
   "type": "singlestat",
   "description": "**mysql 运行状态**\n\nmysql up/ 运行状态",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "运行时长",
   "type": "singlestat",
   "description": "**运行时长**\n\ngloubal Status Threads Running/ 运行时长",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "活跃会话数",
   "type": "singlestat",
   "description": "**gloubal Status Threads Running**\n\ngloubal Status Threads Running/ 活动会话数",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_threads_running{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "singlestat",
   "description": "**Current TPS**\n\n每秒事物量/Transactions Per Second",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(rate(mysql_global_status_commands_total{command=\"commit\",instance=\"$host\"}[$interval])+ on (instance) rate(mysql_global_status_commands_total{command=\"rollback\",instance=\"$host\"}[$interval])) or (rate(mysql_global_status_commands_total{command=\"commit\",instance=\"$host\"}[5m])+ on (instance) rate(mysql_global_status_commands_total{command=\"rollback\",instance=\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool 大小",
   "type": "singlestat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Buffer Pool大小占总内存百分比",
   "type": "singlestat",
   "description": "**InnoDB Buffer Pool Size % of Total RAM**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"} * 100) / on (instance) node_memory_MemTotal_bytes{instance=\"$host\"}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$host\"} )",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_connects{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_connects{instance=\"$host\"}[5m])",
     "legendFormat": "Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_clients{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_clients{instance=\"$host\"}[5m])",
     "legendFormat": "Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "graph",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[5m])",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "graph",
   "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size{instance=\"$host\"}",
     "legendFormat": "Thread Cache Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached{instance=\"$host\"}",
     "legendFormat": "Threads Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_threads_created{instance=\"$host\"}[5m])",
     "legendFormat": "Threads Created"
    }
   ]
  },
  { "title": "Queries and Table Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "MySQL Questions",
   "type": "graph",
   "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_questions{instance=\"$host\"}[5m])",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "graph",
   "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_join{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_full_join{instance=\"$host\"}[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_range_join{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_full_range_join{instance=\"$host\"}[5m])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_range{instance=\"$host\"}[5m])",
     "legendFormat": "Select Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range_check{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_range_check{instance=\"$host\"}[5m])",
     "legendFormat": "Select Range Check"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_scan{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_scan{instance=\"$host\"}[5m])",
     "legendFormat": "Select Scan"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$host\"}[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "graph",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[5m])",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_waited{instance=\"$host\"}[5m])",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  { "title": "Temporary Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "MySQL Temporary Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Created Tmp Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Created Tmp Disk Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_files{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_files{instance=\"$host\"}[5m])",
     "legendFormat": "Created Tmp Files"
    }
   ]
  },
  { "title": "Sorts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "MySQL Sorts",
   "type": "graph",
   "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_rows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_rows{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Rows"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_range{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_scan{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_scan{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Scan"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "graph",
   "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received{instance=\"$host\"}[1h])",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent{instance=\"$host\"}[1h])",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "graph",
   "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_page_size{instance=\"$host\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "Key Buffer Size"
    }
   ]
  },
  { "title": "Command, Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "Main Command Rate",
   "type": "graph",
   "description": "**Top Command Counters Hourly**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=\"delete\"}[$interval]) or irate(mysql_global_status_commands_total{instance=\"$host\",command=\"delete\"}[5m])",
     "legendFormat": "Com_{{ command }}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=\"insert\"}[$interval]) or irate(mysql_global_status_commands_total{instance=\"$host\",command=\"insert\"}[5m])",
     "legendFormat": "Com_{{ command }}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=\"insert_select\"}[$interval]) or irate(mysql_global_status_commands_total{instance=\"$host\",command=\"insert_select\"}[5m])",
     "legendFormat": "Com_{{ command }}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=\"replace\"}[$interval]) or irate(mysql_global_status_commands_total{instance=\"$host\",command=\"replace\"}[5m])",
     "legendFormat": "Com_{{ command }}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=\"replace_select\"}[$interval]) or irate(mysql_global_status_commands_total{instance=\"$host\",command=\"replace_select\"}[5m])",
     "legendFormat": "Com_{{ command }}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=\"select\"}[$interval]) or irate(mysql_global_status_commands_total{instance=\"$host\",command=\"select\"}[5m])",
     "legendFormat": "Com_{{ command }}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=\"update\"}[$interval]) or irate(mysql_global_status_commands_total{instance=\"$host\",command=\"update\"}[5m])",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Files and Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_files{instance=\"$host\"}[5m])",
     "legendFormat": "Openings"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_files{instance=\"$host\"}",
     "legendFormat": "Open Files"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit{instance=\"$host\"}",
     "legendFormat": "Open Files Limit"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{instance=\"$host\"}",
     "legendFormat": "InnoDB Open Files"
    }
   ]
  },
  { "title": "Table Openings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "graph",
   "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "graph",
   "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables{instance=\"$host\"}",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{instance=\"$host\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  { "title": "MySQL Table Definition Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "MySQL Table Definition Cache",
   "type": "graph",
   "description": "**MySQL Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions{instance=\"$host\"}",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{instance=\"$host\"}",
     "legendFormat": "Table Definitions Cache Size"
    },
    {
     "expr": "rate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[5m])",
     "legendFormat": "Opened Table Definitions"
    }
   ]
  },
  { "title": "Slave delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Slave delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_slave_status_seconds_behind_master{instance=\"$host\"}",
     "legendFormat": "seconds_behind_master"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_slave_status_sql_delay{instance=\"$host\"}",
     "legendFormat": "sql_delay"
    }
   ]
  },
  { "title": "InnoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "缓冲池比率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"free\"} / on (instance) mysql_global_status_buffer_pool_page_changes_total{instance=\"$host\",operation=\"total\"}) * 100",
     "legendFormat": "innodb_buf_usage"
    },
    {
     "expr": "100 - (mysql_global_status_innodb_buffer_pool_reads{instance=\"$host\"} / on (instance) mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}) * 100",
     "legendFormat": "innodb_buf_hit"
    },
    {
     "expr": "(mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"dirty\"} / on (instance) mysql_global_status_buffer_pool_page_changes_total{instance=\"$host\",operation=\"total\"}) * 100",
     "legendFormat": "innodb_buf_dirty"
    }
   ]
  },
  {
   "title": "缓冲池读写频率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "缓冲池读取频率"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "缓冲池写入频率"
    }
   ]
  },
  {
   "title": "缓冲池页刷新速率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_buffer_pool_page_changes_total{instance=\"$host\",operation=\"flushed\"}[$interval]) or irate(mysql_global_status_buffer_pool_page_changes_total{instance=\"$host\",operation=\"flushed\"}[5m])",
     "legendFormat": "缓冲池页刷新频率"
    }
   ]
  },
  {
   "title": "Log Buffer刷新频率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_log_waits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_waits{instance=\"$host\"}[5m])",
     "legendFormat": "Log Buffer刷新频率"
    }
   ]
  },
  {
   "title": "InnoDB文件读写频率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_data_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{instance=\"$host\"}[5m])",
     "legendFormat": "文件读取频率"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_data_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{instance=\"$host\"}[5m])",
     "legendFormat": "文件写入频率"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_data_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_read{instance=\"$host\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_data_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_written{instance=\"$host\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "InnoDB行频率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"inserted\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"inserted\"}[5m])",
     "legendFormat": "innodb_ins_row_count"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"deleted\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"deleted\"}[5m])",
     "legendFormat": "innodb_del_row_count"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"updated\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"updated\"}[5m])",
     "legendFormat": "innodb_upd_row_count"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"read\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\",operation=\"read\"}[5m])",
     "legendFormat": "innodb_read_row_count"
    }
   ]
  },
  {
   "title": "InnoDB日志读写频率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_log_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "日志写请求频率"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[5m])",
     "legendFormat": "日志物理写频率"
    },
    {
     "expr": "rate(mysql_global_status_innodb_os_log_fsyncs{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=\"$host\"}[5m])",
     "legendFormat": "日志fsync写频率"
    }
   ]
  },
  {
   "title": "InnoDB读写数据速度",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "none", "label": "Pages/s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[5m])",
     "legendFormat": "读取量"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_pages_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_written{instance=\"$host\"}[5m])",
     "legendFormat": "写入量"
    }
   ]
  },
  {
   "title": "InnoDB行锁",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}",
     "legendFormat": "行锁等待个数"
    },
    {
     "calculatedInterval": "2s",
     "expr": "mysql_global_status_innodb_row_lock_current_waits{instance=\"$host\"}",
     "legendFormat": "当前行锁等待数"
    },
    {
     "expr": "mysql_global_status_innodb_row_lock_time_avg{instance=\"$host\"}",
     "legendFormat": "行锁平均等待时间"
    }
   ]
  },
  {
   "title": "InnoDB写日志文件数据速度",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "none", "label": "Pages/s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[5m])",
     "legendFormat": "写入"
    }
   ]
  },
  { "title": "MyISAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "Key Buffer比率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(mysql_global_status_key_blocks_used{instance=\"$host\"} / on (instance) (mysql_global_status_key_blocks_used{instance=\"$host\"} + mysql_global_status_key_blocks_unused{instance=\"$host\"})) * 100",
     "legendFormat": "myisam_buf_usage"
    },
    {
     "expr": "100 - (mysql_global_status_key_reads{instance=\"$host\"} / on (instance) mysql_global_status_key_read_requests{instance=\"$host\"}) * 100",
     "legendFormat": "myisam_buf_read_hit"
    },
    {
     "expr": "100 - (mysql_global_status_key_writes{instance=\"$host\"} / on (instance) mysql_global_status_key_write_requests{instance=\"$host\"}) * 100",
     "legendFormat": "myisam_buf_write_hit"
    }
   ]
  },
  {
   "title": "硬盘读取频率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 197 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_key_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_reads{instance=\"$host\"}[5m])",
     "legendFormat": "硬盘读取频率"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_key_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_writes{instance=\"$host\"}[5m])",
     "legendFormat": "硬盘写入频率"
    }
   ]
  },
  {
   "title": "缓冲池读写频率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_key_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_read_requests{instance=\"$host\"}[5m])",
     "legendFormat": "缓冲池读取频率"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(mysql_global_status_key_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_key_write_requests{instance=\"$host\"}[5m])",
     "legendFormat": "缓冲池写入频率"
    }
   ]
  }
 ]
}