{
 "title": "PostgreSQL Database",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "node_boot_time_seconds" },
   { "name": "database", "label": "Database", "query": "pg_static" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "主机资源监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "系统启动时间",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=\"$server\"} * 1000",
     "legendFormat": "System Uptime(days)"
    }
   ]
  },
  {
   "title": "CPU 核心数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$server\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$server\"} - (node_memory_MemFree_bytes{instance=\"$server\"} + node_memory_Buffers_bytes{instance=\"$server\"} + node_memory_Cached_bytes{instance=\"$server\"})) / node_memory_MemTotal_bytes{instance=\"$server\"} * 100"
    }
   ]
  },
  {
   "title": "缓存占比",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "(node_memory_Cached_bytes{instance=\"$server\"} * 100) / node_memory_MemTotal_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "系统平均负载 (1,5,15) ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$server\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$server\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "磁盘使用情况",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"})/100 *100"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"} / node_filesystem_size_bytes{instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"})"
    }
   ]
  },
  {
   "title": "磁盘IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops", "label": "reads(+)/ writes(-) " }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{device}}_reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{device}}_writes"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$server\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$server\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{instance=\"$server\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$server\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$server\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$server\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{instance=\"$server\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$server\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=\"$server\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "PostgreSQL数据库监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "PostgreSQL启动时间",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 14 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{instance=\"$database\"} * 1000"
    }
   ]
  },
  {
   "title": "PostgreSQL版本",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 14 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pg_static{instance=\"$database\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Max Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "Logging Collector",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_logging_collector{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Shared_buffers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Effective_cache_size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Work Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Fsync",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_fsync{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "数据库大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "活动会话数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "pg_stat_activity_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(pg_stat_database_tup_fetched{instance=\"$database\"}[$interval]))"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(pg_stat_database_xact_commit{instance=\"$database\"}[$interval]))"
    }
   ]
  },
  {
   "title": "PostgreSQL Table Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{instance=\"$database\",datname!~\"template0|template1|\"} !=0",
     "legendFormat": "{{datname}}/{{mode}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$database\",datname!~\"postgres|template0|template1\"}[5m])",
     "legendFormat": "{{datname}}.deadlocks"
    }
   ]
  },
  {
   "title": "Fetched Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Returned Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "数据库缓存命中率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$database\",datname!~\"postgres|template0|template1\"}/(pg_stat_database_blks_read{instance=\"$database\",datname!~\"postgres|template0|template1\"}+pg_stat_database_blks_hit{instance=\"$database\",datname!~\"postgres|template0|template1\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$database\"}[5m])",
     "legendFormat": "checkpoint_sync_time"
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$database\"}[5m])",
     "legendFormat": "checkpoint_write_time"
    }
   ]
  }
 ]
}